class AgentVO():
    def __init__(self, cid=None,
                 platId=None,
                 agentAccount=None,
                 loginPwd=None,
                 agentName=None,
                 bankName=None,
                 bank=None,
                 bankNo=None,
                 phone=None,
                 email=None,
                 qq=None,
                 wechat=None,
                 retirementId=None,
                 administrativeId=None,
                 feePlanId=None,
                 preferentialCost=None,
                 rebateCost=None,
                 registerDiscountId=None,
                 memberLevelId=None,
                 status=None,
                 joinSource=None,
                 registerIp=None,
                 auditUser=None,
                 auditUsername=None,
                 auditTime=None,
                 auditStatus=None,
                 sourceType=None,
                 isAudit=None,
                 canModify=None
                 ):
        self.cid = cid
        self.platId = platId
        self.agentAccount = agentAccount
        self.loginPwd = loginPwd
        self.agentName = agentName
        self.bankName = bankName
        self.bank = bank
        self.bankNo = bankNo
        self.phone = phone
        self.email = email
        self.qq = qq
        self.wechat = wechat
        self.retirementId = retirementId
        self.administrativeId = administrativeId
        self.feePlanId = feePlanId
        self.preferentialCost = preferentialCost
        self.rebateCost = rebateCost
        self.registerDiscountId = registerDiscountId
        self.memberLevelId = memberLevelId
        self.status = status
        self.joinSource = joinSource
        self.registerIp = registerIp
        self.auditUser = auditUser
        self.auditUsername = auditUsername
        self.auditTime = auditTime
        self.auditStatus = auditStatus
        self.sourceType = sourceType
        self.isAudit = isAudit
        self.canModify = canModify
